#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path_url)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path_url}"

# Restore sources & data
src_path="/var/www/${app}"
sudo cp -a ./sources "$src_path"

# Restore permissions to app files
sudo chown -R root: "$src_path"

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Copy PHP-FPM pool configuration and reload the service
sudo cp -a ./php-fpm.conf "/etc/php5/fpm/pool.d/${app}.conf"
sudo service php5-fpm reload

# Restart webserver
sudo service nginx reload
